// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgqD-6UTUopeC3DQQn6SK2TjcGvOGS2a0',
    appId: '1:1088747968852:web:70d659c539e16cd89e50c1',
    messagingSenderId: '1088747968852',
    projectId: 'cmsc23-todo-app-satusi-c4l',
    authDomain: 'cmsc23-todo-app-satusi-c4l.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-satusi-c4l.appspot.com',
    measurementId: 'G-MKKLSZVKKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_mOm2TlrAt2njU9cQJa1Xdca63COwGoE',
    appId: '1:1088747968852:android:6334266dbb13e9719e50c1',
    messagingSenderId: '1088747968852',
    projectId: 'cmsc23-todo-app-satusi-c4l',
    storageBucket: 'cmsc23-todo-app-satusi-c4l.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEJkZNaPdJD_YEZ_9puD6JWl45hHclK3A',
    appId: '1:1088747968852:ios:a09f6b2289d0bce09e50c1',
    messagingSenderId: '1088747968852',
    projectId: 'cmsc23-todo-app-satusi-c4l',
    storageBucket: 'cmsc23-todo-app-satusi-c4l.appspot.com',
    iosClientId: '1088747968852-5rqujehkf10enbf5gb01o1gfngvtu1df.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEJkZNaPdJD_YEZ_9puD6JWl45hHclK3A',
    appId: '1:1088747968852:ios:a09f6b2289d0bce09e50c1',
    messagingSenderId: '1088747968852',
    projectId: 'cmsc23-todo-app-satusi-c4l',
    storageBucket: 'cmsc23-todo-app-satusi-c4l.appspot.com',
    iosClientId: '1088747968852-5rqujehkf10enbf5gb01o1gfngvtu1df.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
